const WORDS_DATA = [
  {
    word: "accomplish",
    phonetic: "/əˈkʌmplɪʃ/",
    chinese: "v. 完成，实现",
    syllables: ["ac", "com", "plish"],
  },
  {
    word: "adventure",
    phonetic: "/ədˈventʃə(r)/",
    chinese: "n. 冒险，奇遇",
    syllables: ["ad", "ven", "ture"],
  },
  {
    word: "beautiful",
    phonetic: "/ˈbjuːtɪfl/",
    chinese: "adj. 美丽的",
    syllables: ["beau", "ti", "ful"],
  },
  {
    word: "celebrate",
    phonetic: "/ˈselɪbreɪt/",
    chinese: "v. 庆祝",
    syllables: ["cel", "e", "brate"],
  },
  {
    word: "dangerous",
    phonetic: "/ˈdeɪndʒərəs/",
    chinese: "adj. 危险的",
    syllables: ["dan", "ger", "ous"],
  },
  {
    word: "education",
    phonetic: "/ˌedʒuˈkeɪʃn/",
    chinese: "n. 教育",
    syllables: ["ed", "u", "ca", "tion"],
  },
  {
    word: "fantastic",
    phonetic: "/fænˈtæstɪk/",
    chinese: "adj. 极好的",
    syllables: ["fan", "tas", "tic"],
  },
  {
    word: "government",
    phonetic: "/ˈɡʌvənmənt/",
    chinese: "n. 政府",
    syllables: ["gov", "ern", "ment"],
  },
  {
    word: "happiness",
    phonetic: "/ˈhæpinəs/",
    chinese: "n. 幸福",
    syllables: ["hap", "pi", "ness"],
  },
  {
    word: "important",
    phonetic: "/ɪmˈpɔːtnt/",
    chinese: "adj. 重要的",
    syllables: ["im", "por", "tant"],
  },
  {
    word: "knowledge",
    phonetic: "/ˈnɒlɪdʒ/",
    chinese: "n. 知识",
    syllables: ["knowl", "edge"],
  },
  {
    word: "literature",
    phonetic: "/ˈlɪtrətʃə(r)/",
    chinese: "n. 文学",
    syllables: ["lit", "er", "a", "ture"],
  },
  {
    word: "magnificent",
    phonetic: "/mæɡˈnɪfɪsnt/",
    chinese: "adj. 壮丽的",
    syllables: ["mag", "nif", "i", "cent"],
  },
  {
    word: "necessary",
    phonetic: "/ˈnesəsəri/",
    chinese: "adj. 必要的",
    syllables: ["nec", "es", "sary"],
  },
  {
    word: "opportunity",
    phonetic: "/ˌɒpəˈtjuːnəti/",
    chinese: "n. 机会",
    syllables: ["op", "por", "tu", "ni", "ty"],
  },
  {
    word: "population",
    phonetic: "/ˌpɒpjuˈleɪʃn/",
    chinese: "n. 人口",
    syllables: ["pop", "u", "la", "tion"],
  },
  {
    word: "question",
    phonetic: "/ˈkwestʃən/",
    chinese: "n. 问题",
    syllables: ["ques", "tion"],
  },
  {
    word: "responsible",
    phonetic: "/rɪˈspɒnsəbl/",
    chinese: "adj. 负责的",
    syllables: ["re", "spon", "si", "ble"],
  },
  {
    word: "successful",
    phonetic: "/səkˈsesfl/",
    chinese: "adj. 成功的",
    syllables: ["suc", "cess", "ful"],
  },
  {
    word: "technology",
    phonetic: "/tekˈnɒlədʒi/",
    chinese: "n. 技术",
    syllables: ["tech", "nol", "o", "gy"],
  },
  {
    word: "university",
    phonetic: "/ˌjuːnɪˈvɜːsəti/",
    chinese: "n. 大学",
    syllables: ["u", "ni", "ver", "si", "ty"],
  },
  {
    word: "vegetable",
    phonetic: "/ˈvedʒtəbl/",
    chinese: "n. 蔬菜",
    syllables: ["veg", "e", "ta", "ble"],
  },
  {
    word: "wonderful",
    phonetic: "/ˈwʌndəfl/",
    chinese: "adj. 精彩的",
    syllables: ["won", "der", "ful"],
  },
  {
    word: "excellent",
    phonetic: "/ˈeksələnt/",
    chinese: "adj. 优秀的",
    syllables: ["ex", "cel", "lent"],
  },
  {
    word: "yesterday",
    phonetic: "/ˈjestədeɪ/",
    chinese: "n. 昨天",
    syllables: ["yes", "ter", "day"],
  },
  {
    word: "ambition",
    phonetic: "/æmˈbɪʃn/",
    chinese: "n. 雄心，抱负",
    syllables: ["am", "bi", "tion"],
  },
  {
    word: "bachelor",
    phonetic: "/ˈbætʃələ(r)/",
    chinese: "n. 学士；单身汉",
    syllables: ["bach", "e", "lor"],
  },
  {
    word: "candidate",
    phonetic: "/ˈkændɪdət/",
    chinese: "n. 候选人",
    syllables: ["can", "di", "date"],
  },
  {
    word: "democracy",
    phonetic: "/dɪˈmɒkrəsi/",
    chinese: "n. 民主",
    syllables: ["de", "moc", "ra", "cy"],
  },
  {
    word: "enthusiasm",
    phonetic: "/ɪnˈθjuːziæzəm/",
    chinese: "n. 热情",
    syllables: ["en", "thu", "si", "asm"],
  },
];
